main_tests:
  Brightness:
    min: 320
    typ: 360
    max: 400
  Brightness_uniformaty:
    min: 75
    typ: 80
    max: 85
  Contrast:
    min: 955.0
    typ: 1200.0
    max: 1445.0
  Cg_rgb_area:
    min: 65.00
    typ: 70.0
    max: 75.00
  Cg_ntsc_area:
    min: 65
    typ: 70.0
    max: 75
  Cg_rgb:
    min: 90.25
    typ: 95.0
    max: 99.75
  Cg_ntsc:
    min: 100.25
    typ: 110.0
    max: 99.75
  Temperature:
    min: 5096.0
    typ: 6492.0
    max: 9197.0
  Delta_e:
    min: 2
    typ: 3
    max: 4
  Red_x:
    min: 0.647
    typ: 0.677
    max: 0.707
  Red_y:
    min: 0.290
    typ: 0.320
    max: 0.350
  Green_x:
    min: 0.243
    typ: 0.273
    max: 0.303
  Green_y:
    min: 0.630
    typ: 0.660
    max: 0.690
  Blue_x:
    min: 0.119
    typ: 0.149
    max: 0.179
  Blue_y:
    min: 0.025
    typ: 0.054
    max: 0.084
  White_x:
    min: 0.283
    typ: 0.313
    max: 0.343
  White_y:
    min: 0.299
    typ: 0.329
    max: 0.359


