main_tests:
  Brightness:
    min: 270
    typ: 300
    max: 400
  Brightness_uniformity:
    min: 75
    typ: 80
    max: 110
  Contrast:
    min: 1000
    typ: 1500
    max: 5000
  Cg_rgb_area:
    min: 95.0
    typ: 99.0
    max: 150.0
  Cg_ntsc_area:
    min: 71
    typ: 72
    max: 90
  Cg_rgb:
    min: 95
    typ: 99
    max: 150
  Cg_ntsc:
    min: 100
    typ: 110
    max: 120
  Temperature:
    min: 5800
    typ: 6300
    max: 7700
  Delta_e:
    min: 3
    typ: 4
    max: 6
  Red_x:
    min: 0.614
    typ: 0.644
    max: 0.674
  Red_y:
    min: 0.313
    typ: 0.333
    max: 0.362
  Green_x:
    min: 0.266
    typ: 0.296
    max: 0.326
  Green_y:
    min: 0.631
    typ: 0.661
    max: 0.691
  Blue_x:
    min: 0.106
    typ: 0.136
    max: 0.166
  Blue_y:
    min: 0.016
    typ: 0.046
    max: 0.076
  White_x:
    min: 0.283
    typ: 0.313
    max: 0.343
  White_y:
    min: 0.299
    typ: 0.329
    max: 0.359


