# Config for report generator
# General instructions:
#   The file name must match the approved model name, for example SDX-43U4169.yaml
#   In cases where the order number and name of the manufacturing factory must be included in the file name, variants such as SDX-43U4169_CH19 are permitted
#     Where SDX-65U4169 is the model name, CH is the Changhong factory, and 19 is the order number.
# Note:
#   If no requirements to max value, just leave it as None
#   If no requirements to color gamut for one of color space, put the same value as for necessary color space
#   if no requirements you can leave by default values for color accuracy

main_tests:
  Brightness: # Brightness range
    min: 260
    typ: 280
    max: None
  Brightness_uniformity: # Brightness uniformity range
    min: 65
    typ: 68
    max: None
  Contrast: # Contrast ratio range
    min: 3000
    typ: 4000
    max: None
  Cg_rgb_area: # Color gamut percent in sRGB color space
    min: 67
    typ: 72
    max: None
  Cg_ntsc_area: # Color gamut percent in NTSC color space
    min: 67
    typ: 72
    max: None
  Cg_rgb: # Color gamut percent in sRGB color space (more accurate calculation method)
    min: 67
    typ: 72
    max: None
  Cg_ntsc: # Color gamut percent in NTSC color space (more accurate calculation method)
    min: 67
    typ: 72
    max: None
  Temperature: # Color temperature range
    min: 7300
    typ: 9300
    max: 11300
  Delta_e: # Requirements for color accuracy
    min: 4
    typ: 3
    max: 2
  Red_x: # Requirements for color coordinates of Red
    min: 0.542
    typ: 0.642
    max: 0.742
  Red_y:
    min: 0.229
    typ: 0.329
    max: 0.429
  Green_x: # Requirements for color coordinates of Green
    min: 0.199
    typ: 0.299
    max: 0.399
  Green_y:
    min: 0.492
    typ: 0.592
    max: 0.692
  Blue_x: # Requirements for color coordinates of Blue
    min: 0.042
    typ: 0.142
    max: 0.242
  Blue_y:
    min: 0.001
    typ: 0.047
    max: 0.147
  White_x: # Requirements for color coordinates of White
    min: 0.183
    typ: 0.283
    max: 0.383
  White_y:
    min: 0.190
    typ: 0.290
    max: 0.390