sRGB:
  Red:
    x: 0.64
    y: 0.33
  Green:
    x: 0.3
    y: 0.6
  Blue:
    x: 0.15
    y: 0.06
NTSC:
  Red:
    x: 0.67
    y: 0.33
  Green:
    x: 0.22
    y: 0.71
  Blue:
    x: 0.14
    y: 0.08
