# Config for report generator
# General instructions:
#   The file name must match the approved model name, for example SDX-43U4169.yaml
#   In cases where the order number and name of the manufacturing factory must be included in the file name, variants such as SDX-43U4169_CH19 are permitted
#     Where SDX-65U4169 is the model name, CH is the Changhong factory, and 19 is the order number.
# Note:
#   If no requirements to max value, just leave it as None
#   If no requirements to color gamut for one of color space, put the same value as for necessary color space
#   if no requirements you can leave by default values for color accuracy

main_tests:
  Brightness: # Brightness range
    min: 260
    typ: 280
    max: None
  Brightness_uniformity: # Brightness uniformity range
    min: 65
    typ: 68
    max: None
  Contrast: # Contrast ratio range
    min: 3000
    typ: 4000
    max: None
  Cg_rgb_area: # Color gamut percent in sRGB color space
    min: 67
    typ: 72
    max: None
  Cg_ntsc_area: # Color gamut percent in NTSC color space
    min: 67
    typ: 72
    max: None
  Cg_rgb: # Color gamut percent in sRGB color space (more accurate calculation method)
    min: 67
    typ: 72
    max: None
  Cg_ntsc: # Color gamut percent in NTSC color space (more accurate calculation method)
    min: 67
    typ: 72
    max: None
  Temperature: # Color temperature range
    min: 8835
    typ: 9585
    max: 10335
  Delta_e: # Requirements for color accuracy
    min: 4
    typ: 3
    max: 2
  Red_x: # Requirements for color coordinates of Red
    min: 0.608
    typ: 0.638
    max: 0.668
  Red_y:
    min: 0.305
    typ: 0.335
    max: 0.365
  Green_x: # Requirements for color coordinates of Green
    min: 0.297
    typ: 0.307
    max: 0.337
  Green_y:
    min: 0.567
    typ: 0.597
    max: 0.627
  Blue_x: # Requirements for color coordinates of Blue
    min: 0.120
    typ: 0.150
    max: 0.180
  Blue_y:
    min: 0.032
    typ: 0.062
    max: 0.092
  White_x: # Requirements for color coordinates of White
    min: 0.253
    typ: 0.283
    max: 0.313
  White_y:
    min: 0.260
    typ: 0.290
    max: 0.320